### ISSUE TITLE
Release version 1.1.0

### ISSUE THREAD

**Issue by rbraeunlich** [camunda/camunda-bpm-platform-osgi#23] opened 2015-02-02 18:21 UTC
Hi Christian,

could you please release version 1.1.0? The next development version should be 2.0.0.
Also, it would be great if we could provide the Karaf distribution simultaneously. [here](https://groups.google.com/forum/#!topic/camunda-bpm-dev/XlmK5XnojVg)

Cheers,
Ronny

**Comment by hawky-4s-** [comment] 2015-02-12 12:29
@rbraeunlich:

During the maven build of 'camunda-bpm-karaf-feature' the tests fail because karaf is unable to retrieve some necessary artifacts. Probably this works for you because they are already in your local maven repository.
They artifacts in question are:

Error resolving artifactorg.ops4j.pax.exam:pax-exam-features:xml:3.5.0:Could not find artifact org.ops4j.pax.exam:pax-exam-features:xml:3.5.0
and
Error resolving artifactorg.apache.felix:org.apache.felix.metatype:jar:1.0.10:Could not find artifact org.apache.felix:org.apache.felix.metatype:j
ar:1.0.10

To reproduce the bug, just delete the artifacts from your local maven repo and execute the maven build.

**Comment by rbraeunlich** [comment] 2015-02-12 16:43
Hi Christian,

I cannot reporduce the bug. I deleted both directories from my local Maven repository.
After I ran ``mvn clean test`` the test was successful and the Jar/Xml reappeared.

Also, I can see that both are present in Maven Central. Maybe it's some network/firewall/... issue on your side?

Cheers,
Ronny

**Comment by wiax** [comment] 2015-02-12 16:50
Same issue than hawky-4s-

**Comment by rbraeunlich** [comment] 2015-02-16 19:03
Hi Christian,

I hope my latest commit fixes the problem. Could you give it a try, please?

Cheers,
Ronny

**Comment by hawky-4s-** [comment] 2015-02-16 23:36
Hi Ronny,

The commits did not change anything. I've created a ci build on cloudbees buildhive and linked the status badge into the readme. I believe it has something to do with using a mirror in settings.xml. But even without a mirror and a clean maven repository, I was unable to build the project cleanly. Tried from home, work and datacenter jenkins. Everytime artifacts are missing.
With the newest changes I am unable to download following artifact
[WARNING] The POM for org.eclipse:org.eclipse.osgi:jar:3.8.2.v20130124-134944 is missing, no dependency information available.

**Comment by rbraeunlich** [comment] 2015-02-17 19:43
Hi Christian,
after varying the test timeouts a little bit Jenkins seems to be [on my side](https://buildhive.cloudbees.com/job/camunda/job/camunda-bpm-platform-osgi/7/) ;-)
So, what do we do now?

**Comment by gimbel** [comment] 2015-02-18 08:15
Hi Ronny,

Christian is on vacation at the moment. It might take a week for him to reply.

Just wanted to let you know.

Robert

**Comment by hawky-4s-** [comment] 2015-03-03 09:17
HI Ronny,

Could you please have a look at #a81f20ceeda928216dcb9ade197a4a22ecad9cbe and check if I got the dependencies right? I commented some deps which are not tested or joined some deps, e.g. the engine requires the model-* stuff, it's not optional.

Cheers,
Christian

**Comment by rbraeunlich** [comment] 2015-03-03 18:12
Hi Christian,

thank you for your help with the versions. I am quite happy about your help.
I took a look at the changes and have only some minor questions:
* You removed all the dependencies to camunda commons; doesn't the engine need any camunda commons classes any more?
* Since you removed all of the logging bundles, is the engine is back to java.util logging?
* You deleted the "camunda-models" feature and added the bundles to the camunda-core feature. I added the "camunda-models" so the feature.xml looks a little bit more tidy. What about keeping the feature and adding it to "camunda-core"?

Cheers,
Ronny

**Comment by hawky-4s-** [comment] 2015-03-04 13:27
Hi Ronny,

- The engine never needed the commons classes. Only Spin / Connect uses them.
- Engine uses only java.util. Spin / Connect use logging api.
- I merged the models features because the engine does not work without them, they are mandatory. Providing a feature for tidyness, dunno. I'm no OSGi guy in that aspect. Could be done your way if you really want it.

Cheers,
Christian

**Comment by rbraeunlich** [comment] 2015-03-04 15:54
Hi Christian,

my proposal is f95d6b028a4af078ee1fea1000794b098f75dee0
I hope we can agree on that ;)

Cheers,
Ronny

**Comment by hawky-4s-** [comment] 2015-03-04 16:00
Ack. Should I start the release?

Hint: You have to edit the release notes and title of the github release after the maven release. I can only provide a default text, because I must create it before I can attach/upload the karaf files to it.

**Comment by rbraeunlich** [comment] 2015-03-04 16:04
Yes, please.
Thanks for the hint, I'll try to provide something meaningful.
And please remind me the next time we meet to pay for the drinks ;)

**Comment by hawky-4s-** [comment] 2015-03-04 22:06
Hi Ronny,

See https://github.com/camunda/camunda-bpm-platform-osgi/releases/tag/1.1.0 

Cheers,
Christian

**Closed by hawky-4s-** 2015-03-04 22:06 UTC
